### ISSUE TITLE
move `integGenTest.jl` to a standalone package

### ISSUE THREAD

**Issue by SimeonEhrig** [QEDjl-project/QuantumElectrodynamics.jl#27]
During the [JuliaHEP](https://indico.cern.ch/event/1292759/) I got the feedback that the generator for integration tests is quiet interesting and some people wants to use it. Also there is no similar project. Therefore we should move `integGenTest.jl` to an extra project and register it. This makes it easier to reuse it in other projects. Also contribution is much easier.

# Tasks

1. find a better name :grimacing: 
2. move code in a new repository
3. split up project depended from general code like the graph traversing algorithm

**Comment by szabo137** [comment]
What is the status of this one?

**Comment by SimeonEhrig** [comment]
To many other tasks to do :-(
At least, I need to setup the Gitlab CI tests in the repository. Else, I can't remember. If have to check it.

**Comment by SimeonEhrig** [comment]
The package is registered: https://github.com/QEDjl-project/IntegrationTests.jl/issues/23

Let's integrate it in QED.jl
