### ISSUE TITLE
Drop PkgDependency dependency

### ISSUE THREAD

**Issue by AntonReinhard** [QEDjl-project/QuantumElectrodynamics.jl#33]
We should probably drop PkgDependency from our dependencies or request at their package to make some functionality available which is intended for automated use.

Original from PR comment here: https://github.com/QEDjl-project/QED.jl/pull/31#discussion_r1590653446

**Comment by SimeonEhrig** [comment]
`PkgDependency` is only part of the CI tool and if we get rid of, we need to maintain the dependency graph of the QED.jl project by hand.

**Comment by AntonReinhard** [comment]
No, I don't mean to do it manually, I meant to implement the little functionality we actually need from it ourselves so we're safe from random changes in their repository breaking our CI, as happened with their v0.5.0. We could basically just copy their current `builddict()` function.

**Comment by SimeonEhrig** [comment]
Done in `IntegrationTests.jl`
